name: 'Document'
description: 'Run roxygen2::roxygenise() to convert roxygen comments to .Rd files'

runs:
  using: "composite"
  steps:
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::roxygen2
        needs: roxygen2

    - name: Document
      run: roxygen2::roxygenise()
      shell: Rscript {0}

    - name: Commit and push changes
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add man/\* NAMESPACE
        git commit -m "Update documentation" || echo "No changes to commit"
        git pull --ff-only
        git push origin
      shell: bash